package Services;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tns.cg.smms.entities.Customer;
import com.tns.cg.smms.repositories.CustomerRepository;

@Service // This annotation is used to define class as service class which provides buisness logic
@Transactional
public class CustomerService {
	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	CustomerRepository customerRepository;

	// Retreiving all Customers
	public List<Customer> getAllCustomers(){
		return customerRepository.findAll();
	}
	
	// Creating New Customer
	public void save(Customer emp) {
		customerRepository.save(emp);
	}
	
	//  Retreiving customer by id
	public Customer getCustomerById(Integer id) {
		return customerRepository.findById(id).get();
	}
	
	// Deleting customer from database
	public void delete(Integer id) {
		customerRepository.deleteById(id);
	}
}