package Services;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tns.cg.smms.entities.Employee;
import com.tns.cg.smms.repositories.EmployeeRepository;

@Service // This annotation is used to define class as service class which provides buisness logic
@Transactional
public class EmployeeService {

	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	EmployeeRepository employeeRepository;

	// Retreiving all Employees
	public List<Employee> getAllEmployees(){
		return employeeRepository.findAll();
	}
	
	// Creating New Employee
	public void save(Employee emp) {
		employeeRepository.save(emp);
	}
	
	//  Retreiving employee by id
	public Employee getEmployeeById(Integer id) {
		return employeeRepository.findById(id).get();
	}
	
	// Deleting Employee from database
	public void delete(Integer id) {
		employeeRepository.deleteById(id);
	}
}
