package Services;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tns.cg.smms.entities.MallAdmin;
import com.tns.cg.smms.repositories.MallAdminRepository;

@Service
@Transactional
public class MallAdminService {
	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	MallAdminRepository adminRepository;
	
	// Retreiving all Admins
	public List<MallAdmin> getAllAdmins(){
		return adminRepository.findAll();
	}
	
	// Creating New Admin
	public void save(MallAdmin emp) {
		adminRepository.save(emp);
	}
	
	//  Retreiving admin by id
	public MallAdmin getAdminById(Integer id) {
		return adminRepository.findById(id).get();
	}
	
	// Deleting Admin from database
	public void delete(Integer id) {
		adminRepository.deleteById(id);
	}
}
