package Services;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tns.cg.smms.entities.ShopOwner;
import com.tns.cg.smms.repositories.ShopOwnerRepository;

@Service
@Transactional
public class ShopOwnerService {
	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	ShopOwnerRepository sRepository;
	
	// Retreiving all Owners
	public List<ShopOwner> getAllOwners(){
		return sRepository.findAll();
	}
	
	// Creating New Owner
	public void save(ShopOwner emp) {
		sRepository.save(emp);
	}
	
	//  Retreiving owner by id
	public ShopOwner getOwnerById(Integer id) {
		return sRepository.findById(id).get();
	}
	
	// Deleting owner from database
	public void delete(Integer id) {
		sRepository.deleteById(id);
	}
}