package Services;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tns.cg.smms.entities.User;
import com.tns.cg.smms.repositories.UserRepository;

@Service
@Transactional
public class UserService {
	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	UserRepository uRepository;
	
	// Retreiving all Users
	public List<User> getAllUsers(){
		return uRepository.findAll();
	}
	
	// Creating New User
	public void save(User emp) {
		uRepository.save(emp);
	}
	
	//  Retreiving user by id
	public User getUserById(Integer id) {
		return uRepository.findById(id).get();
	}
	
	// Deleting user from database
	public void delete(Integer id) {
		uRepository.deleteById(id);
	}
}
